[package]
name = "pman"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"

[dev-dependencies]
tempfile = "3.10"
